### ISSUE TITLE
Building the operator requires the code to live in GOPATH

### ISSUE THREAD

**Issue by asmigala** [teiid/teiid-operator#13]
Trying to build the operator when cloned to an arbitrary directory yields:
```
./hack/go-build.sh
/home/asmigala/src/teiid-operator is not within a known GOPATH/src
FATA[0000] dependency manager "dep" requires working directory to be in $GOPATH/src 
```

Moving the cloned directory to `~/go/src/` works.

I have very limited knowledge of go and dep, but I believe there is a way to make it work in other directories (syndesis operator can be built right from its source dir).

**Comment by shawkins** [comment]
I see this as well.  I think we need to migrate from dep to using modules.  Just setting GO111MODULE=on makes things get further, but I still hit this because of dep.

**Comment by shawkins** [comment]
This still won't work for me.  Using:

go version go1.12.12 linux/amd64

This still fails with compile errors - starting with the logs issue.

**Comment by rareddy** [comment]
I updated to `go version go1.12.13 linux/amd64` then issuing `make` worked fine.

**Comment by shawkins** [comment]
I'll need to try with a downgrade of go.  I would guess that it's a caching issue with your builds.  You should try cleaning everything - something like: go clean -modcache -cache ./...

and rebuilding
