### ISSUE TITLE
Hello-world VDB does not build (ownerReference invalid in build config)

### ISSUE THREAD

**Issue by jhoeflaken** [teiid/teiid-operator#191]
I have installed the Teiid Operator 0.4 in Openshift 4.5.7 en created the hello world virutal database. It keeps in the state **Ready for S2I**

Looking the operator log I see that it cannot create the _virutal-database_ build configuration because of an empty or missing ownerReference.
 
{"level":"info","ts":"2020-09-10T08:53:01.863960713Z","logger":"virtualdatabase","msg":"Creating a new BuildConfig virtualdatabase-builder in namespace data-virtualization"}
{"level":"error","ts":"2020-09-10T08:53:01.872124663Z","logger":"virtualdatabase","msg":"Failed during action S2IBuilderImageAction BuildConfig.build.openshift.io \"virtualdatabase-builder\" is invalid: [metadata.ownerReferences.name: Invalid value: \"\": name must not be empty, metadata.ownerReferences.uid: Invalid value: \"\": uid must not be empty]"}

Am I missing something?

**Comment by jhoeflaken** [comment]
This only happens when installing the operator globally in the openshift-operator  namespace. When installing the operator in a specific namespace it does work.

**Comment by rareddy** [comment]
yes, code has not been fixed for the global namespace yet.

**Comment by jhoeflaken** [comment]
Close
