### ISSUE TITLE
0.1.0 not in quay.io

### ISSUE THREAD

**Issue by shawkins** [teiid/teiid-operator#37]
The update from 0.0.1 to 0.1.0 was incomplete as the tagged operator image was not created.

**Comment by shawkins** [comment]
using the documented operator courier command I could create a tagged teiid/teiid application, but nothing seems to show up as a new operator: https://quay.io/repository/teiid/teiid-operator?tag=latest&tab=tags

**Comment by rareddy** [comment]
using the deploy script should push the image to quay

**Comment by shawkins** [comment]
Which deploy script?  Following the readme got me 

https://quay.io/application/teiid/teiid - look on the right hand side. but nothing here:
https://quay.io/repository/teiid/teiid-operator?tag=latest&tab=tags

**Comment by rareddy** [comment]
make deploy

**Comment by shawkins** [comment]
Okay that seems to work: https://quay.io/repository/teiid/teiid-operator?tab=tags

But starting down the path of converting to modules wasn't quite successful.  See https://github.com/teiid/teiid-operator/pull/38
