### ISSUE TITLE
How to add private Maven repositories with credentials

### ISSUE THREAD

**Issue by jhoeflaken** [teiid/teiid-operator#81]
Hello,

I don't know if this is the place but I am playing around with the Teiid operator and was wondering if it was possible to add a private Maven repositories with credentials. We're using our own Nexus and know that you can add a Maven repository to the VirtualDatabase resource, but I cannot figure out how  to provide credentials.

Kind regards,

Jacob

**Comment by rareddy** [comment]
Unfortunately, it does not have the feature to provide the secrets yet for private nexus repo, can you open a JIRA at https://issues.redhat.com/projects/TEIIDTOOLS/summary for this, I will see if I can add this.

**Comment by jhoeflaken** [comment]
Done. TEIID-950.

Thnx.

Kind regards,

Jacob
________________________________

**Comment by rareddy** [comment]
Will continue this in TEIIDTOOLS-950
